// Auto-generated by hippy from axpy.hippy
// Generated scaffold — edit freely from here on.
#include <hip/hip_runtime.h>
#include <cstdio>
#include <cstdlib>

template<typename T>
struct GPUBuffer {
    T* ptr = nullptr;
    size_t n = 0;

    GPUBuffer() = default;
    explicit GPUBuffer(size_t n_) : n(n_) {
        hipMalloc(&ptr, n * sizeof(T));
    }
    ~GPUBuffer() {
        if (ptr) hipFree(ptr);
    }

    // movable, not copyable (owns a device allocation)
    GPUBuffer(const GPUBuffer&) = delete;
    GPUBuffer& operator=(const GPUBuffer&) = delete;
    GPUBuffer(GPUBuffer&& other) noexcept : ptr(other.ptr), n(other.n) {
        other.ptr = nullptr;
    }

    void upload(const T* host) {
        hipMemcpy(ptr, host, n * sizeof(T), hipMemcpyHostToDevice);
    }
    void download(T* host) {
        hipMemcpy(host, ptr, n * sizeof(T), hipMemcpyDeviceToHost);
    }

    operator T*() { return ptr; }
};

inline int hippy_blocks(int n, int threads = 256) {
    return (n + threads - 1) / threads;
}

// ---- constants ----
constexpr int N = 1024;
constexpr int n = N;

// ---- kernels ----

__global__ void axpy(float a, float* x, float* y, int n) {
    int i = (blockIdx.x * blockDim.x + threadIdx.x);  // TODO: hippy guessed 'int' for i; fix the type if wrong
    if (i < n) {
        y[i] = a * x[i];
    }
}

// ---- host code ----
int main() {
    float a = 2.0f;
    float h_x[N];
    for (int i = 0; i < N; i++) h_x[i] = 1.0f;
    float h_y[N];
    for (int i = 0; i < N; i++) h_y[i] = 0.0f;

    GPUBuffer<float> x(N);
    GPUBuffer<float> y(N);

    x.upload(h_x);  // TODO: ensure h_x is your host-side array
    y.upload(h_y);  // TODO: ensure h_y is your host-side array

    axpy<<<hippy_blocks(N, 256), 256>>>(a, x, y, n);
    hipDeviceSynchronize();  // TODO: remove if you're handling sync/streams yourself

    y.download(h_y);  // TODO: ensure h_y is your host-side array

    return 0;
}