// Auto-generated by hippy from sum_sines.hippy
// Generated scaffold — edit freely from here on.
#include "../error_checking.hpp"
#include <cstdlib>

inline int hippy_blocks(int n, int threads = 256) {
    return (n + threads - 1) / threads;
}

// ---- constants ----
constexpr int N = 100000;

// ---- kernels ----

__global__ void sum_sines(float* a, int n) {
    int i = (blockIdx.x * blockDim.x + threadIdx.x);  // TODO: hippy guessed 'int' for i; fix the type if wrong
    if (i < n) {
        atomicAdd(a, sinf((float)i));
    }
}

// ---- host code ----
int main() {
    float h_a[1];
    for (int i = 0; i < 1; i++) h_a[i] = 0.0f;

    float *d_a = nullptr;
    HIP_ERRCHK(hipMalloc(&d_a, 1 * sizeof(float)));

    HIP_ERRCHK(hipMemcpy(d_a, h_a, 1 * sizeof(float), hipMemcpyHostToDevice));

    sum_sines<<<hippy_blocks(N, 256), 256>>>(d_a, N);
    HIP_ERRCHK(hipGetLastError());
    HIP_ERRCHK(hipDeviceSynchronize());

    HIP_ERRCHK(hipMemcpy(h_a, d_a, 1 * sizeof(float), hipMemcpyDeviceToHost));

    {
        const int _show = 4;
        printf("a:");
        if (1 <= 2 * _show) {
            for (int _i = 0; _i < 1; _i++) printf(" %g", h_a[_i]);
        } else {
            for (int _i = 0; _i < _show; _i++) printf(" %g", h_a[_i]);
            printf(" ...");
            for (int _i = 1 - _show; _i < 1; _i++) printf(" %g", h_a[_i]);
        }
        printf("\n");
    }

    HIP_ERRCHK(hipFree(d_a));

    return 0;
}